### ISSUE TITLE
[Feature]: (Un)Archive Actions on EditRecord

### ISSUE THREAD

**Issue by AurelDemiri** [okeonline/filament-archivable#2]
### What happened?

It would be nice to have archive/unarchive actions when editing a record.

PS: Request a feature button in the Github issues tab does not work. I think you need to enable discussions in repo settings. 

### How to reproduce the bug

.

### Package Version

1.0.1

### PHP Version

8.3

### Laravel Version

11

**Comment by rvzug** [comment]
Would you like to make/are planning to make this feature? You're welcome to add it through a PR. More people are suggesting this, so I might add it if the community does not add it.

**Comment by rvzug** [comment]
See v1.1.0
