### ISSUE TITLE
[Feature]: Archive Child Assets

### ISSUE THREAD

**Issue by AElleray** [okeonline/filament-archivable#7]
### What happened?

When archiving a Parent item. none of the Child assets are archived
is there a setting to archive relationships 

### How to reproduce the bug

When archiving a Parent item. none of the Child assets are archived
is there a setting to archive relationships 

### Package Version

2.0.0

### PHP Version

8.2.0

### Laravel Version

9.0.0

**Comment by rvzug** [comment]
Hi, at this moment we don't support 'touching' relations, as in archiving them. Also, the Archivable plugin (https://github.com/joelbutcher/laravel-archivable) does not support it. This package is only a Filament-representation of the archived items by that plugin.

For *cascading **soft deletes*** there is a package: https://github.com/michaeldyrynda/laravel-cascade-soft-deletes. Maybe you can look into that package to see how cascading archiving could work: 

Add to the parent model boot-method:
```php
// be sure the relation() exists and has the Archivable-trait and `archived_at` column
static::archived(function (Model $model) {
    $model->relation()->archive();       
});
```
